name: google_map_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.10
  location: ^5.0.3
  flutter_polyline_points: ^2.1.0
  geocoding: ^2.0.4
  http: ^1.2.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: 
  uses-material-design: true
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
